deploy, bashrc: download 'spark' command line tool to $HOME/bin
'spark' is a command line which can create rudimentary graphs using
block characters e.g.

spark 1 2 3 4
▁▃▅█

I also export $HOME/bin to my PATH in bashrc so I can use 'spark' without
it's file path.

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -40,4 +40,14 @@ else
     mv config "$HOME/.config/terminator/"
 fi
 
+# OTHER EXECUTABLES
+[ ! -d "${HOME}/bin" ] && { echo "Creating ${HOME}/bin"; mkdir "${HOME}/bin"; }
+
+# SPARK (command line graphs)
+echo "Downloading 'spark'"
+{ curl --silent \
+  https://raw.github.com/holman/spark/master/spark > "${HOME}/bin/spark" &&
+  chmod a+x "${HOME}/bin/spark"
+} || { rm -f "${HOME}/bin/spark"; echo "Failed to download 'spark'"; }
+
 echo 'Done'
